AWSTemplateFormatVersion: "2010-09-09"
Description: Create RDS

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  SystemName:
    Description: "System name of each resource names."
    Type: String
    Default: "gr"

  EnvName:
    Description: "Environment name of each resource names."
    Type: String
    Default: "product"

  RDSMasterUserName:
    Description: RDS DB Master User Name.
    Default: "grsys"
    Type: String

  RDSMasterPassword:
    Description: RDS DB Master Password.
    Type: String
    NoEcho: true

  RDSMaintenanceWindow:
    Description: Enter MaintenanceWindow(UTC)
    Type: String
    Default: "sat:18:00-sat:19:00"

# ------------------------------------------------------------#
# Create RDS
# ------------------------------------------------------------#
Resources:

  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      DBInstanceIdentifier: !Sub ${SystemName}-${EnvName}-rds
      DBName: "grdb"

      Engine: mysql
      EngineVersion: "8.0"

      DBInstanceClass: db.t3.micro   # ✅ 프리티어
      AllocatedStorage: "20"
      StorageType: "gp2"

      MasterUsername: !Ref RDSMasterUserName
      MasterUserPassword: !Ref RDSMasterPassword

      Port: 3306
      PubliclyAccessible: false

      MultiAZ: false
      AutoMinorVersionUpgrade: false

      BackupRetentionPeriod: 1   # ✅ 안정 설정 (0보다 안전)

      PreferredMaintenanceWindow: !Ref RDSMaintenanceWindow

      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${EnvName}-rds-sg

      DBSubnetGroupName: !Ref RDSSubnetGroup

      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvName}-rds
        - Key: Env
          Value: !Sub ${EnvName}

# ------------------------------------------------------------#
# Create SubnetGroup
# ------------------------------------------------------------#
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub ${SystemName}-${EnvName}-dbsub-v2
      DBSubnetGroupDescription: !Sub ${SystemName}-${EnvName}-dbsub Subnet Group
      SubnetIds:
        - Fn::ImportValue: !Sub ${EnvName}-datastore-subnet-1a
        - Fn::ImportValue: !Sub ${EnvName}-datastore-subnet-1b
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvName}-dbsub
        - Key: Env
          Value: !Sub ${EnvName}

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  RDSInstance:
    Value: !Ref RDSInstance
    Export:
      Name: !Sub ${SystemName}-rds